Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2019-06, with the labels that each got.

#1910 Bugfix/cleanup filter xml
  content/src/main/content/META-INF/vault/filter.xml
Labels: technical enhancement

#1864 Proposed fix for #1856: Allow specifying Spreadsheet locale.
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/data/Spreadsheet.java
  bundle/src/main/java/com/adobe/acs/commons/data/Variant.java
  bundle/src/main/java/com/adobe/acs/commons/data/package-info.java
  bundle/src/test/java/com/adobe/acs/commons/data/SpreadsheetTest.java
Labels: bug

#1933 Fix broken paint connections in Version Compare
  CHANGELOG.md
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/clientlibs/js/app.js
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/graph.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/options.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/page-header.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/version-compare.jsp
Labels: bug

#1939 Adjust InvalidateAllNodesVisitorTest, AllEntryNodesCountVisitorTest, ExpiredNodesVisitorTest, RenovatorTest, TotalCacheSizeVisitorTest to Java 11
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/AllEntryNodesCountVisitorTest.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/ExpiredNodesVisitorTest.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/InvalidateAllNodesVisitorTest.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/TotalCacheSizeVisitorTest.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/renovator/RenovatorTest.java
Labels: technical enhancement

#1943 Adjust InvalidateByCacheConfigVisitorTest for Java 11
  bundle/src/main/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/InvalidateByCacheConfigVisitor.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/InvalidateByCacheConfigVisitorTest.java
Labels: technical enhancement

#1937 Adjust PropertiesTest to Java 11
  bundle/src/test/java/com/adobe/acs/commons/wcm/comparisons/impl/PropertiesTest.java
Labels: technical enhancement

#1940 Adjust EntryNodeMapVisitorTest to Java 11
  bundle/src/main/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/EntryNodeMapVisitor.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/EntryNodeMapVisitorTest.java
Labels: technical enhancement

#1936 Adjust VersionServiceImplTest to Java 11
  bundle/src/test/java/com/adobe/acs/commons/wcm/comparisons/impl/VersionServiceImplTest.java
Labels: technical enhancement

#1938 Adjust EntryNodeByStringKeyVisitorTest to Java 11
  bundle/src/main/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/EntryNodeByStringKeyVisitor.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/visitor/EntryNodeByStringKeyVisitorTest.java
Labels: technical enhancement

#1958 Adjust WorkflowPackageManagerImplTest to Java 11
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java
  bundle/src/test/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImplTest.java
Labels: technical enhancement

#1957 Adjust MultiFieldPanelWCMUseTest to Java 11
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/widgets/MultiFieldPanelWCMUse.java
  bundle/src/main/java/com/adobe/acs/commons/widgets/package-info.java
  bundle/src/test/java/com/adobe/acs/commons/widgets/MultiFieldPanelWCMUseTest.java
Labels: technical enhancement

#1926 Adjust PageCompareDataImplTest to Java 11
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/wcm/comparisons/impl/PageCompareDataImpl.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/comparisons/impl/PageCompareDataImplTest.java
Labels: technical enhancement

#1927 Feature/httpcache response cookie exclusion
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/httpcache/config/HttpCacheConfig.java
  bundle/src/main/java/com/adobe/acs/commons/httpcache/config/impl/HttpCacheConfigImpl.java
  bundle/src/main/java/com/adobe/acs/commons/httpcache/config/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/httpcache/engine/impl/HttpCacheEngineImpl.java
  bundle/src/main/java/com/adobe/acs/commons/httpcache/util/CacheUtils.java
  bundle/src/main/java/com/adobe/acs/commons/httpcache/util/package-info.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/engine/impl/HttpCacheEngineImplTest.java
Labels: enhancement

#1969 Feature/data importer create node enhancement (#1945)
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/DataImporter.java
Labels: enhancement
