Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2019-03, with the labels that each got.

#1775 Issue #1774 Upgraded oakpal to v1.2.0 for OSGi compatibility
  CHANGELOG.md
  oakpal-checks/pom.xml
  oakpal-checks/src/main/java/com/adobe/acs/commons/oakpal/checks/AcsCommonsAuthorizableCompatibilityCheck.java
  oakpal-checks/src/main/java/com/adobe/acs/commons/oakpal/checks/CompatBaseFactory.java
  oakpal-checks/src/main/java/com/adobe/acs/commons/oakpal/checks/ContentClassifications.java
  oakpal-checks/src/main/java/com/adobe/acs/commons/oakpal/checks/RecommendEnsureAuthorizable.java
  oakpal-checks/src/main/java/com/adobe/acs/commons/oakpal/checks/RecommendEnsureOakIndex.java
  oakpal-checks/src/test/java/com/adobe/acs/commons/oakpal/checks/RecommendEnsureAuthorizableTest.java
  pom.xml
Labels: technical enhancement

#1783 Added the possibility to replace the existing host in an attribute
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/StaticReferenceRewriteTransformerFactory.java
  bundle/src/test/java/com/adobe/acs/commons/rewriter/impl/StaticReferenceRewriteTransformerFactoryTest.java
Labels: enhancement

#1766 Feature/test user exporter
  bundle/pom.xml
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/Parameters.java
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/UsersExportServlet.java
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/UsersInitServlet.java
  bundle/src/test/java/com/adobe/acs/commons/exporters/impl/users/UserExportServletTest.java
  bundle/src/test/java/com/adobe/acs/commons/exporters/impl/users/UsersInitServletTest.java
  bundle/src/test/java/com/adobe/acs/commons/exporters/impl/users/UsersSaveServletTest.java
Labels: technical enhancement

#1776 fix possibly negative index
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/functions/RoundRobin.java
  bundle/src/test/java/com/adobe/acs/commons/functions/RoundRobinTest.java
Labels: bug

#1782 Feature/1762 - DAM Copy Publish URL
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/dam/impl/CopyAssetPublishUrlFeature.java
  bundle/src/test/java/com/adobe/acs/commons/dam/impl/CopyAssetPublishUrlFeatureTest.java
  content/src/main/content/META-INF/vault/filter.xml
  content/src/main/content/jcr_root/apps/acs-commons/authoring/dam-copy-publishurl/css.txt
  content/src/main/content/jcr_root/apps/acs-commons/authoring/dam-copy-publishurl/dam-copy-publish-url.css
  content/src/main/content/jcr_root/apps/acs-commons/authoring/dam-copy-publishurl/dam-copy-publish-url.js
  content/src/main/content/jcr_root/apps/acs-commons/authoring/dam-copy-publishurl/js.txt
  content/src/main/content/jcr_root/apps/acs-commons/renderconditons/ispublished/ispublished.jsp
  content/src/main/content/jcr_root/apps/dam/gui/content/assets/metadataeditor/.content.xml
Labels: bug, undocumented

#1785 #1709 - Fixes issue with ACS AEM Commons utility page's header bars n…
  CHANGELOG.md
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/app-page/app-page.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/exporters/users-to-csv/clientlibs/css/app.less
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/oak-index-manager/content.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/page-compare/page-compare.jsp
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/version-compare/version-compare.jsp
Labels: bug

#1792 #1791 - Asset Folder Creator to support non-string cell types (ie. Nu…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/AssetFolderCreator.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/AssetFolderCreatorTest.java
  bundle/src/test/resources/com/adobe/acs/commons/mcp/impl/processes/asset-folder-creator.xlsx
Labels: bug

#1793 #1528 - Fixed issues with Workflow Remover's OlderThan not working.
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/WorkflowInstanceRemover.java
  bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/impl/WorkflowInstanceRemoverImpl.java
  bundle/src/main/java/com/adobe/acs/commons/workflow/bulk/removal/package-info.java
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/workflow-remover/clientlibs/js/app.js
  content/src/main/content/jcr_root/apps/acs-commons/components/utilities/workflow-remover/includes/form.jsp
Labels: bug

#1794 1539 - Removed used QueryBuilder references
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/errorpagehandler/impl/ErrorPageHandlerImpl.java
  bundle/src/main/java/com/adobe/acs/commons/packaging/impl/QueryPackagerServletImpl.java
  bundle/src/main/java/com/adobe/acs/commons/util/impl/QueryHelperImpl.java
Labels: enhancement
