Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2019-07, with the labels that each got.

#1973 Adding vanity URL and URL rewrite support to SiteMap
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java
Labels: enhancement

#1959 trying to fix intermittent test failures (fix #1941)
  bundle/src/main/java/com/adobe/acs/commons/fam/impl/ThrottledTaskRunnerImpl.java
  bundle/src/test/java/com/adobe/acs/commons/fam/impl/ThrottledTaskRunnerTest.java
Labels: technical enhancement

#1987 #1547 - Updated Report Runner's ReportCSVExportServlet to support ext…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/reports/internal/ReportCSVExportServlet.java
Labels: bug

#1968 Adjust JCRHttpCacheStoreImplTest to Java 11
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/httpcache/store/jcr/impl/JCRHttpCacheStoreImpl.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/JCRHttpCacheStoreImplTest.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/JCRHttpCacheStoreMocks.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/store/jcr/impl/mock/JCRHttpCacheStoreMocks.java
Labels: technical enhancement

#1952 Adjust I18nProviderImplTest to Java 11
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/i18n/impl/I18nProviderImpl.java
  bundle/src/test/java/com/adobe/acs/commons/i18n/impl/I18nProviderImplTest.java
Labels: technical enhancement
