Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2020-01, with the labels that each got.

#2152 Fixes #2146 - Truncating the cell value if too long
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/TagReporter.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/TagReportTest.java
  bundle/src/test/resources/com/adobe/acs/commons/mcp/impl/processes/lotsofchildren.json
Labels: bug, enhancement

#2142 Correctly evaluate If-None-Match header
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/etag/impl/EtagMessageDigestServletFilter.java
  bundle/src/test/java/com/adobe/acs/commons/etag/impl/EtagMessageDigestServletFilterTest.java
Labels: bug

#2133 Update testing libraries
  CHANGELOG.md
  bundle/pom.xml
  bundle/src/test/java/com/adobe/acs/commons/filefetch/impl/FileFetchImplTest.java
  bundle/src/test/java/com/adobe/acs/commons/httpcache/config/impl/HttpCacheConfigImplTest.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/AssetFolderCreatorTest.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/comparisons/impl/VersionServiceImplTest.java
  pom.xml
Labels: technical enhancement

#2144 Feature/add functionality showhidedialogfields
  ui.apps/src/main/content/jcr_root/apps/acs-commons/touchui-widgets/showhidedialogfields/source/showhidedialogfieldstabs.js
Labels: bug, enhancement

#2174 Add more granular environment indicator css control - take 2
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/cloudconfig/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/marketo/client/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/marketo/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/workflow/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilter.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/impl/AemEnvironmentIndicatorFilterTest.java
  pom.xml
Labels: enhancement
