Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2020-12, with the labels that each got.

#2489 Add possibility to use a specified http scheme for the static referen…
  bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/StaticReferenceRewriteTransformerFactory.java
Labels: enhancement

#2487 Dispatcher Flush Re-Fetch: issues/2478
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/replication/dispatcher/DispatcherFlushFilter.java
  bundle/src/main/java/com/adobe/acs/commons/replication/dispatcher/impl/RefetchFlushContentBuilderImpl.java
  bundle/src/test/java/com/adobe/acs/commons/replication/dispatcher/impl/RefetchFlushContentBuilderImplTest.java
Labels: enhancement, new feature

#2485 Feature/generic lists asset metadata json
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/genericlists/impl/GenericListImpl.java
  bundle/src/main/java/com/adobe/acs/commons/genericlists/package-info.java
Labels: enhancement

#2246 Remove Automatic Package Replication UI
  CHANGELOG.md
  RELEASING.md
  bundle/pom.xml
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/TreeReplication.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/TreeReplicationFactory.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/renovator/Renovator.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/AutomaticPackageReplicator.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/AutomaticPackageReplicatorMBean.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/AutomaticPackageReplicationHealthCheck.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/AutomaticPackageReplicatorImpl.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/AutomaticPackageReplicatorJob.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/ConfigurationUpdateListener.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/ErrorLoggingProgressListener.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/EventBasedAutomaticPackageReplicator.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/FilteredEventBasedAutomaticPackageReplicator.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/ReplicatePackageProcess.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/impl/ScheduledAutomaticPackageReplicator.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/model/AutomaticPackageReplicatorModel.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/model/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/replication/packages/automatic/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/util/ResourceServiceManager.java
  bundle/src/main/java/com/adobe/acs/commons/util/mbeans/ResourceServiceManagerMBean.java
  bundle/src/main/java/com/adobe/acs/commons/util/mbeans/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/util/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/RobotsServlet.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/SiteMapServlet.java
  bundle/src/main/java/com/adobe/acs/commons/workflow/impl/WorkflowPackageManagerImpl.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/TreeReplicationTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/AutomaticPackageReplicatiorHealthCheckTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/AutomaticPackageReplicatorTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/EventBasedAutomaticPackageReplicatorTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/FilteredEventBasedAutomaticPackageReplicatorTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/ReplicatePackageProcessTest.java
  bundle/src/test/java/com/adobe/acs/commons/replication/packages/automatic/impl/ScheduledAutomaticPackageReplicatorTest.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/impl/RobotsServletTest.java
  bundle/src/test/java/io/wcm/testing/mock/aem/MockPageManagerFactory.java
  bundle/src/test/resources/com/adobe/acs/commons/replication/packages/automatic/configurations.json
  content/pom.xml
  oakpal-checks/pom.xml
  pom.xml
  ui.apps/pom.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/clientlibs/app.css
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/clientlibs/app.js
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/clientlibs/css.txt
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/clientlibs/js.txt
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/automatic-package-replication/content.jsp
  ui.apps/src/main/content/jcr_root/apps/acs-commons/templates/utilities/automatic-package-replication/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/templates/utilities/automatic-package-replication/thumbnail.png
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/automatic-package-replication/.content.xml
  ui.content/pom.xml
  ui.content/src/main/content/META-INF/vault/filter.xml
  ui.content/src/main/content/jcr_root/etc/acs-commons/automatic-package-replication/.content.xml
Labels: enhancement, pinned, technical enhancement

#2342 #2341 - Removed /var resources from ui.content package
  CHANGELOG.md
  ui.apps/src/main/content/jcr_root/apps/acs-commons/config.author/org.apache.sling.jcr.repoinit.RepositoryInitializer-acs-aem-commons-author.config
  ui.apps/src/main/content/jcr_root/apps/acs-commons/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-acs-aem-commons-all.config
  ui.apps/src/main/content/jcr_root/apps/acs-commons/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-acs-commons.xml
  ui.content/src/main/content/META-INF/vault/filter.xml
  ui.content/src/main/content/jcr_root/home/users/system/acs-commons/httpcache-jcr-storage-provider/.content.xml
  ui.content/src/main/content/jcr_root/home/users/system/acs-commons/manage-controlled-processes/.content.xml
  ui.content/src/main/content/jcr_root/home/users/system/acs-commons/on-deploy-scripts-service/.content.xml
  ui.content/src/main/content/jcr_root/home/users/system/acs-commons/workflow-package-manager-service/.content.xml
  ui.content/src/main/content/jcr_root/home/users/system/acs-commons/workflow-remover/.content.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/httpcache/.content.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/httpcache/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/httpcache/root/.content.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/mcp/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/on-deploy-scripts-status/.content.xml
  ui.content/src/main/content/jcr_root/var/acs-commons/on-deploy-scripts-status/README.txt
  ui.content/src/main/content/jcr_root/var/acs-commons/on-deploy-scripts-status/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/workflow/instances/_rep_policy.xml
  ui.content/src/main/content/jcr_root/var/workflow/packages/_rep_policy.xml
Labels: bug, technical enhancement

#2365 Moving reports from /var/acs-commons/reports to /conf/acs-commons-reports
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/app-page/clientlibs/css/notifications.less
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/report-builder/report-list-page/content.jsp
  ui.content/src/main/content/META-INF/vault/filter.xml
  ui.content/src/main/content/jcr_root/conf/acs-commons/reports/_rep_policy.xml
  ui.content/src/main/content/jcr_root/conf/acs-commons/reports/sample-component-instances/.content.xml
  ui.content/src/main/content/jcr_root/conf/acs-commons/reports/sample-components-report/.content.xml
  ui.content/src/main/content/jcr_root/conf/acs-commons/reports/sample-page-report/.content.xml
  ui.content/src/main/content/jcr_root/conf/acs-commons/reports/sample-references-report/.content.xml
Labels: AEM Cloud Service, enhancement
