Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2020-07, with the labels that each got.

#2345 Incorrect Injectors ordering with service.ranking #2344 - fix service…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/ChildResourceFromRequestInjector.java
  bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/HierarchicalPagePropertyInjector.java
  bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/I18nInjector.java
  bundle/src/main/java/com/adobe/acs/commons/models/injectors/impl/JsonValueMapValueInjector.java
  bundle/src/test/java/com/adobe/acs/commons/it/build/ScrMetadataIT.java
Labels: bug

#2351 #2350 - Fixed null check in VanityServiceUrlImpl, Added hook for Van…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/VanityURLServiceImpl.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/VanityUrlAdjuster.java
  bundle/src/test/java/com/adobe/acs/commons/it/build/ScrMetadataIT.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/vanity/impl/VanityURLServiceImplTest.java
Labels: bug, enhancement

#2304 #2303 - EnsureOakIndexServlet (exposed via the OSGi Console) should b…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexServlet.java
  bundle/src/main/resources/com/adobe/acs/commons/oak/impl/EnsureOakIndexServlet_doGet.html
  bundle/src/test/java/com/adobe/acs/commons/it/build/ScrMetadataIT.java
  bundle/src/test/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexServletTest.java
Labels: enhancement

#2323 Removed DynamicDeck dependency on deprecated package com.day.cq.dam.api.collection which causes problems w/ AEM CS deployments.
  .gitignore
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/indesign/dynamicdeckdynamo/utils/DynamicDeckUtils.java
Labels: bug, technical enhancement

#2358 #2357 - Added safeguards to SMTPMailServiceHealthCheck to help avoid …
  .gitignore
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/hc/impl/SMTPMailServiceHealthCheck.java
  bundle/src/test/java/com/adobe/acs/commons/hc/impl/SMTPMailServiceHealthCheckTest.java
Labels: enhancement

#2355 Feature/2354 - ACS AEM Commons web console
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/dispatcher-flush/configuration/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/system-notifications/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/createpagewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/createtemplatewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/folderproperties/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/movepagewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/properties/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/publishpagewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/publishtemplatewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/templates/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/templates/properties/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/unpublishpagewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/unpublishtemplatewizard/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/console/versionhistory/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/bulk-workflow-manager/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/content-packagers/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/dispatcher-flush/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/exporters/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/redirect-maps/.content.xml
  ui.apps/src/main/content/jcr_root/apps/cq/core/content/nav/tools/acs-commons/system-notifications/.content.xml
Labels: enhancement

#2356 Feature/ms office asset selector
  CHANGELOG.md
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/asset-selector.html
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/css.txt
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/js.txt
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/resources/icon.png
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/scripts.js
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/asset-selector/clientlibs/styles.less
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/page/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/readme/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/readme/readme.html
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/resources/powerpoint_manifest.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/resources/word_manifest.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/template/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/asset-selectors/ms-office/template/page/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/content/office-addin/powerpoint_manifest.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/content/office-addin/readme/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/content/office-addin/word_manifest.xml
  ui.content/src/main/content/jcr_root/conf/_rep_policy.xml
Labels: new feature

#2369 fix a bunch of SCR warnings
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/audit_log_search/impl/AuditLogSearchServlet.java
  bundle/src/main/java/com/adobe/acs/commons/dam/impl/AssetsFolderPropertiesSupport.java
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/UsersExportServlet.java
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/UsersInitServlet.java
  bundle/src/main/java/com/adobe/acs/commons/exporters/impl/users/UsersSaveServlet.java
  bundle/src/main/java/com/adobe/acs/commons/ondeploy/impl/OnDeployExecutorImpl.java
  bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/StylesheetInlinerTransformerFactory.java
  bundle/src/main/java/com/adobe/acs/commons/users/impl/EnsureAuthorizableManagerImpl.java
  bundle/src/main/java/com/adobe/acs/commons/util/datadefinitions/impl/JcrValidNameDefinitionBuilderImpl.java
  bundle/src/main/java/com/adobe/acs/commons/util/datadefinitions/impl/LocalizedTitleDefinitionBuilderImpl.java
  bundle/src/main/java/com/adobe/acs/commons/util/datadefinitions/impl/LowercaseWithDashesDefinitionBuilderImpl.java
  bundle/src/main/java/com/adobe/acs/commons/util/datadefinitions/impl/TitleAndNodeNameDefinitionBuilderImpl.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/ComponentHelperImpl.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/QrCodeServlet.java
  bundle/src/main/java/com/adobe/acs/commons/wcm/properties/shared/impl/SharedComponentPropertiesImpl.java
Labels: technical enhancement
