Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2020-05, with the labels that each got.

#2301 Feature/2300 - Fixed CopyProperties WF Process copy of empty properties
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/workflow/process/impl/CopyPropertiesProcess.java
  bundle/src/test/java/com/adobe/acs/commons/workflow/process/impl/CopyPropertiesProcessTest.java
  bundle/src/test/resources/com/adobe/acs/commons/workflow/process/impl/CopyPropertiesProcessTest.json
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/workflow/copy-properties/_cq_dialog/.content.xml
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/workflow/copy-properties/_cq_editConfig.xml
Labels: bug

#2317 Adding new annotation processor for generated dialogs
  bundle/pom.xml
  bundle/src/main/java/com/adobe/acs/commons/mcp/DialogResourceProviderConfiguration.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/DialogResourceProviderFactory.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/DialogProvider.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/DialogProviderAnnotationProcessor.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/DialogResourceProvider.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/GeneratedDialog.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/form/package-info.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/DialogResourceProviderFactoryImpl.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/DialogResourceProviderImpl.java
  bundle/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  bundle/src/test/java/com/adobe/acs/commons/mcp/DialogResourceProviderFactoryTest.java
  bundle/src/test/resources/com/adobe/acs/commons/mcp/impl/processes/lotsofchildren.json
  pom.xml
Labels: technical enhancement

#2319 #2298 - Removed DynamicDeck dependency on deprecated package com.day.…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/indesign/dynamicdeckdynamo/utils/DynamicDeckUtils.java
Labels: bug, technical enhancement
