Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2024-10, with the labels that each got.

#3425 #3423 Redirect Manager - status code is not retaining its value in the dialog after authoring
  CHANGELOG.md
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/manage-redirects/clientlibs/app.js
Labels: bug

#3419 Content Sync: add an option to disable recursion and sync a single page
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/contentsync/impl/LastModifiedStrategy.java
  bundle/src/test/java/com/adobe/acs/commons/contentsync/impl/TestLastModifiedStrategy.java
  ui.apps/src/main/content/jcr_root/apps/acs-commons/content/contentsync/.content.xml
Labels: new feature

#3415 Allow Robots.txt generation to enable different file by path
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/wcm/impl/RobotsServlet.java
  bundle/src/test/java/com/adobe/acs/commons/wcm/impl/RobotsServletTest.java
Labels: new feature

#3416 #3413 - Redirect Manager: Interface triggers an error because of wrong deprecated resource type
  CHANGELOG.md
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/manage-redirects/clientlibs/app.js
  ui.apps/src/main/content/jcr_root/apps/acs-commons/components/utilities/manage-redirects/redirect-row/redirect-row.html
Labels: bug

#3439 #3438 - Fix bug where duplicate scheme is added to rewritten url value
  bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/StaticReferenceRewriteTransformerFactory.java
  bundle/src/test/java/com/adobe/acs/commons/rewriter/impl/StaticReferenceRewriteTransformerFactoryTest.java
Labels: bug, Skip-Changelog

#3406 Replace RequestResponseFactory by Sling Request builders
  CHANGELOG.md
  bundle/bnd.bnd
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/RefreshFolderThumbnailsFactory.java
  bundle/src/main/java/com/adobe/acs/commons/mcp/impl/processes/RefreshFolderTumbnails.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/cfi/MockContentFragment.java
  bundle/src/test/java/com/adobe/acs/commons/mcp/impl/processes/cfi/MockFragmentData.java
  pom.xml
Labels: technical enhancement

#3450 Adjusted exclusions to use regex, and force Cloud Manager-required pa…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/errorpagehandler/impl/ErrorPageHandlerImpl.java
  bundle/src/test/java/com/adobe/acs/commons/errorpagehandler/impl/ErrorPageHandlerImplTest.java
  pom.xml
Labels: Skip-Changelog

#3422 Remove dependency to commons.lang for Cloud Service
  CHANGELOG.md
  bundle-cloud/pom.xml
  bundle-cloud/src/main/java/com/adobe/acs/commons/email/impl/MailTemplateManagerImpl.java
  bundle-onprem/pom.xml
  bundle-onprem/src/main/java/com/adobe/acs/commons/email/impl/MailTemplateManagerImpl.java
  bundle/src/main/java/com/adobe/acs/commons/email/impl/EmailServiceImpl.java
  bundle/src/main/java/com/adobe/acs/commons/email/impl/MailTemplateManager.java
  bundle/src/main/java/com/adobe/acs/commons/hc/impl/SMTPMailServiceHealthCheck.java
  bundle/src/test/java/com/adobe/acs/commons/email/impl/EmailServiceImplTest.java
  bundle/src/test/java/com/adobe/acs/commons/hc/impl/SMTPMailServiceHealthCheckTest.java
  pom.xml
Labels: technical enhancement
