Repository Adobe-Consulting-Services/acs-aem-commons, pull requests merged in 2024-08, with the labels that each got.

#3405 Update aemanalyser-m-p to 1.6.4
  all/pom.xml
Labels: Skip-Changelog

#3402 Creations or updates of EnsureOakIndex configurations get picked up
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndex.java
  bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexManagerImpl.java
Labels: bug

#3275 CCVAR: Fixed Same Attribute not updating correctly
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/ContentVariableTransformer.java
  bundle/src/test/java/com/adobe/acs/commons/rewriter/impl/ContentVariableTransformerFactoryTest.java
Labels: bug

#3372 #3357 - Added debugging and null checking to ReferencesModel to preven…
  CHANGELOG.md
  bundle/src/main/java/com/adobe/acs/commons/reports/models/ReferencesModel.java
Labels: technical enhancement
